name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: kittn888
        password: ${{ secrets.TOKEN }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          kittn888/my-music:${{ steps.get_version.outputs.VERSION }}
          kittn888/my-music:latest
